default_stages: [pre-commit]
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        additional_dependencies: []
        args: [--fast]
        always_run: true
        stages: [pre-commit]
        pass_filenames: true

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        always_run: true
        stages: [pre-commit]
        pass_filenames: true
